https://online-edu.mirea.ru/pluginfile.php?file=%2F1236105%2Fmod_resource%2Fcontent%2F0%2F%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B0%D1%8F%20%D1%82%D0%B5%D1%82%D1%80%D0%B0%D0%B4%D1%8C%202.pdf

1.1 Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
import numpy as np
chess = np.zeros((8,8),dtype=int)
chess[1::2,::2] = 1
chess[0::2,1::2] = 1
print(chess)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.2 Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.


In [ ]:
import numpy as np
matrix = np.zeros((5,5),int)
matrix += np.arange(5,dtype=int)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3 Создать массив 3x3x3 со случайными значениями.

In [ ]:
import numpy as np
matrix = np.random.random((3,3,3))*10
for i in range(3):
    for j in range(3):
        for k in range(3):
            matrix[i][j][k] = int(matrix[i][j][k])
print(matrix)

[[[9. 9. 5.]
  [8. 5. 6.]
  [2. 7. 7.]]

 [[6. 1. 7.]
  [6. 0. 2.]
  [3. 8. 1.]]

 [[5. 6. 3.]
  [1. 3. 1.]
  [9. 5. 4.]]]


1.4 Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
import numpy as np
matrix = np.ones((10,10),dtype=int)
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


1.5 Создайте массив и отсортируйте его по убыванию.

In [ ]:
import numpy as np
length = 25
matrix = np.random.random((length))
matrix = sorted(matrix, reverse=True)
for i in range(length):
    matrix[i] = int(100*matrix[i])
print(matrix)

[99, 96, 95, 89, 89, 84, 80, 71, 59, 55, 55, 54, 52, 51, 43, 42, 42, 42, 34, 34, 34, 29, 22, 6, 5]


1.6 Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
import numpy as np
a, b = int(input('Кол-во строк: ')), int(input('Кол-во столбцов: '))
matrix = np.random.random((a,b))
for i in range(a):
    for j in range(b):
        matrix[i][j] = int(100*matrix[i][j])
print(matrix)
print(np.shape(matrix))
print(np.size(matrix))
print(np.ndim(matrix))

Кол-во строк: 5
Кол-во столбцов: 8
[[26. 66. 98. 58. 74. 98. 43. 88.]
 [69. 74. 49. 86. 86. 70.  5. 37.]
 [44. 28. 30. 27. 49. 38. 89. 39.]
 [51. 15. 52. 12. 20. 91. 11. 98.]
 [59. 40.  9.  0. 83. 87. 80. 98.]]
(5, 8)
40
2


2.1 Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [ ]:
import pandas as pd
a = pd.Series([4, 3, 10])
b = pd.Series([1, 3, 6])
sm = (sum((a - b)**2))**0.5
print(sm)

5.0


2.2 Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe

age         workclass  education_num      marital_status  \
0       39         State-gov             13       Never-married   
1       50  Self-emp-not-inc             13  Married-civ-spouse   
2       38           Private              9            Divorced   
3       53           Private              7  Married-civ-spouse   
4       28           Private             13  Married-civ-spouse   
...    ...               ...            ...                 ...   
45217   33           Private             13       Never-married   
45218   39           Private             13            Divorced   
45219   38           Private             13  Married-civ-spouse   
45220   44           Private             13            Divorced   
45221   35      Self-emp-inc             13  Married-civ-spouse   

              occupation   relationship   race  gender  hours_per_week  \
0           Adm-clerical  Not-in-family  White    Male              40   
1        Exec-managerial        Husband  White    Male              13   
2      Handlers-cleaners  Not-in-family  White    Male              40   
3      Handlers-cleaners        Husband  Other    Male              40   
4         Prof-specialty           Wife  Other  Female              40   
...                  ...            ...    ...     ...             ...   
45217     Prof-specialty      Own-child  White    Male              40   
45218     Prof-specialty  Not-in-family  White  Female              36   
45219     Prof-specialty        Husband  White    Male              50   
45220       Adm-clerical      Own-child  Other    Male              40   
45221    Exec-managerial        Husband  White    Male              60   

      native_country  capital income_status  
0      United-States     2174         <=50K  
1      United-States        0         <=50K  
2      United-States        0         <=50K  
3      United-States        0         <=50K  
4              Other        0         <=50K  
...              ...      ...           ...  
45217  United-States        0         <=50K  
45218  United-States        0         <=50K  
45219  United-States        0         <=50K  
45220  United-States     5455         <=50K  
45221  United-States        0          >50K  

[45222 rows x 12 columns]

2.3 Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
print('Голова:')
print(dataframe.head(2))
print()
print()
print('Хвост:')
print(dataframe.tail(3))
print()
print()
print('Размер:')
print(dataframe.shape)
print()
print()
print('Описательная статистика для числовых столбцов:')
print(dataframe.describe())
print()
print()
print('Срез фрейма данных:')
print(dataframe.iloc[1:4])
print()
print()
print('Отбор строи фрейма на основе некоторого условия:')
print(dataframe[dataframe['relationship'] == 'Husband'].head(2))

Голова:
   age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K  


Хвост:
       age     workclass  education_num      marital_status       occupation  \
45219   38       Private             13  Married-civ-spouse   Prof-specialty   
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45219      Husband  White   Male              50  United-States     

3.1 Задания нет!

In [ ]:
print('Задания нет!')

Задания нет!


3.2 Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
scaler = MinMaxScaler()
dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
scaler = StandardScaler()
dataframe[['sepal_width_cm']] = scaler.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]